import { type CSSProperties, useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { createAggregateBoard, focusLabel, getAggregateView, type AggregateDimension, type AggregateMetric, type AggregateView, type CreateAggregateBoard, type ServerBoard } from './api';
import { metricLabels, qualityColors, qualityLabels, type QualityStatus } from './data';
import './aggregate.css';

const dimensions: Record<AggregateDimension,string> = {pop:'POP',isp:'ISP',state:'Estado / UF',media_id:'Mídia',device_type:'Tipo de device'};
const metrics: Record<AggregateMetric,string> = {startup_error_rate:metricLabels.startup_error_rate,buffer_ratio:metricLabels.buffer_ratio,join_time_ms_avg:'Join time médio',join_over_sla_pct:'Joins acima do SLA'};
const statusLabel=(status:QualityStatus)=>qualityLabels[status];
const errorText=(error:unknown)=>error instanceof Error?error.message:'Não foi possível carregar os dados.';
const toLocalValue=(date:Date)=>{const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);};
const durationFor=(value:string)=>{const match=/^(\d+)(m|h|d)$/.exec(value);if(!match)return 300_000;const n=Number(match[1]);return n*(match[2]==='m'?60_000:match[2]==='h'?3_600_000:86_400_000);};
const floorDate=(date:Date,granularity:string)=>new Date(Math.floor(date.getTime()/durationFor(granularity))*durationFor(granularity));
const formatCount=(value:number)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(value);
const formatValue=(metric:AggregateMetric,value:number|null|undefined)=>value==null?'Sem dados':metric==='join_time_ms_avg'?`${new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(value)} ms`:`${(value*100).toFixed(2)}%`;
const formatTime=(value:string,granularity:string)=>{const date=new Date(value);return new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',...(durationFor(granularity)>=86_400_000?{day:'2-digit',month:'2-digit'}:{})}).format(date);};
const metricBand=(view:AggregateView,metric:AggregateMetric)=>metric==='join_time_ms_avg'?view.board.slas.join_time_ms:metric==='join_over_sla_pct'?view.board.slas.join_over_sla_pct:view.board.slas[metric];

export function AggregateCreateForm({boards,onCancel,onCreated}:{boards:ServerBoard[];onCancel:()=>void;onCreated:(path:string)=>void}) {
 const now=floorDate(new Date(),'5m'),sixHoursAgo=new Date(now.getTime()-6*60*60*1000);
 const [name,setName]=useState(''),[focusType,setFocusType]=useState<AggregateDimension>('isp'),[focusValue,setFocusValue]=useState(''),[primary,setPrimary]=useState<AggregateDimension>('pop'),[secondary,setSecondary]=useState<AggregateDimension|''>('media_id'),[granularity,setGranularity]=useState('5m'),[from,setFrom]=useState(toLocalValue(sixHoursAgo)),[to,setTo]=useState(toLocalValue(now));
 const [system,setSystem]=useState('npaw'),[sourceQuery,setSourceQuery]=useState(''),[samplingMethod,setSamplingMethod]=useState<'none'|'random'|'stratified'|'systematic'|'unknown'>('none'),[coverage,setCoverage]=useState('1'),[counting,setCounting]=useState<'touch'|'unique'>('touch'),[sessionsBoard,setSessionsBoard]=useState('');
  const [startupWarning,setStartupWarning]=useState('0.02'),[startupCritical,setStartupCritical]=useState('0.05'),[bufferWarning,setBufferWarning]=useState('0.005'),[bufferCritical,setBufferCritical]=useState('0.01'),[joinWarning,setJoinWarning]=useState('8000'),[joinCritical,setJoinCritical]=useState('15000'),[joinOverWarning,setJoinOverWarning]=useState(''),[joinOverCritical,setJoinOverCritical]=useState('');
 const [saving,setSaving]=useState(false),[error,setError]=useState('');
 const sessionsBoards=boards.filter(board=>board.board_type==='sessions');
 async function submit(){
  if(!focusValue.trim()){setError('Informe o valor do foco.');return;}
  const step=durationFor(granularity),fromMs=new Date(from).getTime(),toMs=new Date(to).getTime();
  if(!Number.isFinite(fromMs)||!Number.isFinite(toMs)||fromMs>=toMs){setError('Informe uma janela válida, com início anterior ao fim.');return;}
  if(fromMs%step!==0||toMs%step!==0){setError(`Alinhe início e fim aos intervalos de ${granularity}.`);return;}
  const focus:CreateAggregateBoard['focus']=focusType==='isp'?{type:'isp',isp:focusValue.trim()}:focusType==='pop'?{type:'pop',pop:focusValue.trim()}:focusType==='state'?{type:'state',state:focusValue.trim()}:focusType==='media_id'?{type:'media_id',media_id:focusValue.trim()}:{type:'device_type',device_type:focusValue.trim()};
   const body:CreateAggregateBoard={board_type:'aggregate',name:name.trim(),focus,primary_dimension:primary,...(secondary?{secondary_dimension:secondary}:{}),granularity,window:{from:new Date(from).toISOString(),to:new Date(to).toISOString()},slas:{startup_error_rate:{warning:Number(startupWarning),critical:Number(startupCritical)},buffer_ratio:{warning:Number(bufferWarning),critical:Number(bufferCritical)},join_time_ms:{warning:Number(joinWarning),critical:Number(joinCritical)},...(joinOverWarning.trim()!==''&&joinOverCritical.trim()!==''?{join_over_sla_pct:{warning:Number(joinOverWarning),critical:Number(joinOverCritical)}}:{})},source:{system:system.trim(),query:sourceQuery.trim(),sampling:{method:samplingMethod.trim(),coverage:Number(coverage)},counting},...(sessionsBoard?{linked_sessions_board_id:sessionsBoard}:{})};
  setSaving(true);setError('');try{const board=await createAggregateBoard(body);onCreated(board.view_path);}catch(cause){setError(errorText(cause));}finally{setSaving(false);}
 }
 return <form className="boards-create" onSubmit={event=>{event.preventDefault();void submit();}}>
  <div className="boards-section-heading"><div><h2>Novo board agregado</h2><p>Defina o recorte e a proveniência dos buckets que o agente vai enviar.</p></div><button type="button" className="boards-button" onClick={onCancel}>Cancelar</button></div>
  <div className="boards-form-grid aggregate-create-grid">
   <label>Nome<input required maxLength={100} value={name} onChange={event=>setName(event.target.value)}/></label>
   <label>Foco<select value={focusType} onChange={event=>setFocusType(event.target.value as AggregateDimension)}>{Object.entries(dimensions).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
   <label>{dimensions[focusType]}<input required maxLength={128} value={focusValue} onChange={event=>setFocusValue(event.target.value)}/></label>
   <label>Granularidade<select value={granularity} onChange={event=>{const next=event.target.value;setGranularity(next);setFrom(value=>toLocalValue(floorDate(new Date(value),next)));setTo(value=>toLocalValue(floorDate(new Date(value),next)));}}>{['1m','5m','15m','30m','1h','6h','1d'].map(item=><option key={item}>{item}</option>)}</select></label>
   <label>Início<input required type="datetime-local" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Fim<input required type="datetime-local" value={to} onChange={event=>setTo(event.target.value)}/></label>
   <label>Dimensão principal<select value={primary} onChange={event=>{const next=event.target.value as AggregateDimension;setPrimary(next);if(next===secondary)setSecondary('');}}>{Object.entries(dimensions).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
   <label>Dimensão secundária<select value={secondary} onChange={event=>setSecondary(event.target.value as AggregateDimension|'')}><option value="">Nenhuma</option>{Object.entries(dimensions).map(([key,label])=><option key={key} value={key} disabled={key===primary}>{label}</option>)}</select></label>
  </div>
  <div className="aggregate-create-section"><h3>Proveniência</h3><div className="boards-form-grid aggregate-source-grid">
   <label>Sistema<input required maxLength={100} value={system} onChange={event=>setSystem(event.target.value)}/></label>
   <label>Consulta de origem<textarea required maxLength={8000} rows={3} placeholder="select views, bufferRatio, join_over_sla_metric where datetime between ... group by extraparam15" value={sourceQuery} onChange={event=>setSourceQuery(event.target.value)}/></label>
   <label>Método de amostragem<select value={samplingMethod} onChange={event=>setSamplingMethod(event.target.value as typeof samplingMethod)}>{['none','random','stratified','systematic','unknown'].map(item=><option key={item}>{item}</option>)}</select></label>
   <label>Cobertura (0–1)<input required type="number" min="0" max="1" step="any" value={coverage} onChange={event=>setCoverage(event.target.value)}/></label>
   <label>Contagem de plays<select value={counting} onChange={event=>setCounting(event.target.value as 'touch'|'unique')}><option value="touch">Touch: conta cada POP tocado</option><option value="unique">Único: plays distintos</option></select></label>
   <label>Board de sessões para evidência<select value={sessionsBoard} onChange={event=>setSessionsBoard(event.target.value)}><option value="">Sem vínculo</option>{sessionsBoards.map(board=><option key={board.id} value={board.id}>{board.name}</option>)}</select></label>
  </div><p>Com touch, um play pode aparecer em mais de um POP. Os totais por POP podem superar o total do ISP.</p><p>Inícios e fins precisam estar alinhados à granularidade escolhida.</p></div>
   <div className="aggregate-create-section"><h3>SLAs</h3><p>Taxas usam 0–1 (0,02 = 2%); join time usa milissegundos. Joins acima do SLA são opcionais e habilitam a métrica correspondente na view.</p><div className="boards-sla-form">
    {[["Erro de startup · atenção",startupWarning,setStartupWarning,'ratio'],["Erro de startup · crítico",startupCritical,setStartupCritical,'ratio'],["Buffer ratio · atenção",bufferWarning,setBufferWarning,'ratio'],["Buffer ratio · crítico",bufferCritical,setBufferCritical,'ratio'],["Join time · atenção (ms)",joinWarning,setJoinWarning,'ms'],["Join time · crítico (ms)",joinCritical,setJoinCritical,'ms']].map(([label,value,setter,unit])=><label key={String(label)}>{String(label)}<input required type="number" min="0" max={unit==='ratio'?'1':'86400000'} step="any" value={String(value)} onChange={event=>(setter as (value:string)=>void)(event.target.value)}/></label>)}
    <label>Joins &gt; SLA · atenção (0–1)<input type="number" min="0" max="1" step="any" value={joinOverWarning} placeholder="Opcional" onChange={event=>setJoinOverWarning(event.target.value)}/></label>
    <label>Joins &gt; SLA · crítico (0–1)<input type="number" min="0" max="1" step="any" value={joinOverCritical} placeholder="Opcional" onChange={event=>setJoinOverCritical(event.target.value)}/></label>
   </div></div>
  {error&&<p role="alert">{error}</p>}<button disabled={saving} className="boards-primary">{saving?'Criando…':'Criar board agregado'}</button>
 </form>;
}

export function AggregateBoardDetail({board,userId}:{board:Extract<ServerBoard,{board_type:'aggregate'}>;userId:string|null}) {
 const dimensionOptions=useMemo(()=>Array.from(new Set<AggregateDimension>([board.primary_dimension,...(board.secondary_dimension?[board.secondary_dimension]:[]),...(board.primary_dimension==='pop'||board.secondary_dimension==='pop'?['state' as const]:[])])),[board.primary_dimension,board.secondary_dimension]);
 const [dimension,setDimension]=useState<AggregateDimension>(board.primary_dimension),[metric,setMetric]=useState<AggregateMetric>('buffer_ratio'),[offset,setOffset]=useState(0),[timeOffset,setTimeOffset]=useState(0),[selected,setSelected]=useState<{key:string;ts:string}|null>(null),[filterDimension,setFilterDimension]=useState<AggregateDimension>(board.secondary_dimension??board.primary_dimension),[filterEntity,setFilterEntity]=useState('');
  const allowedMetrics=(['startup_error_rate','buffer_ratio','join_time_ms_avg','join_over_sla_pct'] as const).filter(name=>name==='join_time_ms_avg'?!!board.slas.join_time_ms:name==='join_over_sla_pct'?!!board.slas.join_over_sla_pct:!!board.slas[name]);
 const activeMetric=allowedMetrics.includes(metric)?metric:(allowedMetrics[0]??'startup_error_rate');
 const activeFilters=filterEntity.trim()?[{dimension:filterDimension,entity:filterEntity.trim()}]:[];
 const mainOptions={dimension,metric:activeMetric,filters:activeFilters,offset,limit:10,time_offset:timeOffset,time_limit:36};
 const query=useQuery({queryKey:['aggregate-board-view',userId,board.id,mainOptions],queryFn:()=>getAggregateView(board.id,mainOptions),refetchInterval:15000});
 const filterOptionsQuery=useQuery({queryKey:['aggregate-board-filter-options',userId,board.id,filterDimension,activeMetric],queryFn:()=>getAggregateView(board.id,{dimension:filterDimension,metric:activeMetric,offset:0,limit:100,time_offset:0,time_limit:1}),enabled:filterDimension!==dimension,staleTime:30000});
 const view=query.data;
 const timeBuckets=Array.from(new Set(view?.heatmap.entities.flatMap(entity=>entity.cells.map(cell=>cell.ts))??[])).sort();
 const cells=view?.heatmap.entities.flatMap(entity=>entity.cells.map(cell=>({entity,cell})))??[];
 const selectedEntry=cells.find(item=>item.entity.dim_key===selected?.key&&item.cell.ts===selected?.ts);
 const ranking=[...(view?.ranking??[])].sort((a,b)=>(b.impact_score??-1)-(a.impact_score??-1)||b.volume-a.volume);
 const baselineFor=(ts:string)=>view?.baseline.find(point=>point.ts===ts);
 const coverage=board.source.sampling.coverage;
 const sample=coverage<1;
 const heatmapPages=!!view?.heatmap.next_offset;
 const hasMoreTime=view?.heatmap.next_time_offset!==null&&view?.heatmap.next_time_offset!==undefined;
 const filterOptions=filterDimension===dimension?view?.heatmap.entities:filterOptionsQuery.data?.heatmap.entities;
  function qualityFor(status:QualityStatus):'startup_error'|'warning_buffer'|'critical_buffer'|'warning_join'|'critical_join'|'any_sla_violation' {
   if(activeMetric==='startup_error_rate')return 'startup_error';
   if(activeMetric==='buffer_ratio')return status==='bad'?'critical_buffer':'warning_buffer';
   if(activeMetric==='join_over_sla_pct')return status==='bad'?'critical_join':'warning_join';
   return status==='bad'?'critical_join':'warning_join';
  }
 function drilldownHref(entity:{dim_key:string;label:string},ts:string,status:QualityStatus){
  if(!board.linked_sessions_board_id||status==='unknown'||status==='good')return undefined;
  const rowDimension=view?.heatmap.dimension??dimension;
  const filters=[...(view?.filters??[]).filter(filter=>filter.dimension!==rowDimension),{dimension:rowDimension,entity:entity.label}];
  const query=new URLSearchParams({filters:JSON.stringify(filters),time_from:ts,time_to:new Date(new Date(ts).getTime()+durationFor(view?.effective_granularity??board.granularity)).toISOString(),quality:qualityFor(status)});
  return `/dashboard/boards/${encodeURIComponent(board.linked_sessions_board_id)}?${query.toString()}`;
 }
 if(query.isPending)return <div className="boards-page">Carregando métricas agregadas…</div>;
 if(!view||query.error)return <div className="boards-page"><p role="alert">{errorText(query.error)}</p><button className="boards-button" onClick={()=>void query.refetch()}>Tentar novamente</button></div>;
 const warning=metricBand(view,activeMetric)?.warning;
 const critical=metricBand(view,activeMetric)?.critical;
 return <div className="aggregate-page">
  <div className="aggregate-title-row"><div><div className="boards-eyebrow">AGGREGATE · {board.source.system.toUpperCase()}</div><h1>{board.name}</h1><p>{focusLabel(board)} · {new Date(board.window.from).toLocaleString('pt-BR')} — {new Date(board.window.to).toLocaleString('pt-BR')}</p></div><span className={sample?'aggregate-badge sample':'aggregate-badge complete'}>{sample?`Amostra · ${(coverage*100).toFixed(1)}%`:'Cobertura declarada · 100%'}</span></div>
  <Provenance board={board} coverage={coverage}/>
  <div className="aggregate-controls"><label>Métrica<select value={activeMetric} onChange={event=>{setMetric(event.target.value as AggregateMetric);setSelected(null);setOffset(0);setTimeOffset(0);}}>{allowedMetrics.map(name=><option key={name} value={name}>{metrics[name]}</option>)}</select></label><label>Linhas por dimensão<select value={dimension} onChange={event=>{const next=event.target.value as AggregateDimension;setDimension(next);setOffset(0);setTimeOffset(0);setSelected(null);setFilterDimension(next===board.primary_dimension?(board.secondary_dimension??board.primary_dimension):board.primary_dimension);setFilterEntity('');}}>{dimensionOptions.map(item=><option key={item} value={item}>{dimensions[item]}{item===board.primary_dimension?' · principal':item===board.secondary_dimension?' · secundária':' · regional'}</option>)}</select></label><label>Filtrar {dimensions[filterDimension]}<input list="aggregate-filter-options" value={filterEntity} placeholder="Todas" onChange={event=>{setFilterEntity(event.target.value);setOffset(0);setTimeOffset(0);setSelected(null);}}/><datalist id="aggregate-filter-options">{(filterOptions??[]).map(item=><option key={item.dim_key} value={item.label} label={`${item.label} · ${formatCount(item.volume)} plays`}/>)}</datalist></label><span className="aggregate-window">Resolução: {view.effective_granularity}{view.coarsened?` (solicitada ${view.requested_granularity})`:''}</span></div>
  <section className="aggregate-heatmap-panel"><div className="aggregate-panel-heading"><div><h2>Saúde por entidade e horário</h2><p>Linhas ordenadas por volume; cada célula mostra a banda SLA e os plays no bucket.</p></div><span>{view.heatmap.total} entidades</span></div>
   <div className="aggregate-legend">{(['good','warning','bad','unknown'] as const).map(status=><span key={status}><i style={{background:qualityColors[status]}}/>{statusLabel(status)}</span>)}</div>
   {!view.heatmap.entities.length?<div className="aggregate-empty">Ainda não há buckets para este recorte.</div>:<div className="aggregate-table-scroll"><table className="aggregate-heatmap"><thead><tr><th>{dimensions[view.heatmap.dimension]} / volume</th>{timeBuckets.map(ts=><th key={ts}>{formatTime(ts,view.effective_granularity)}</th>)}</tr></thead><tbody>{[...view.heatmap.entities].sort((a,b)=>b.volume-a.volume).map(entity=><tr key={entity.dim_key}><th scope="row"><strong>{entity.label}</strong><small>{formatCount(entity.volume)} plays</small></th>{timeBuckets.map(ts=>{const cell=entity.cells.find(item=>item.ts===ts);if(!cell)return <td key={ts} className="aggregate-missing" aria-label="Sem dados"/>;const href=drilldownHref(entity,cell.ts,cell.status);const contents=<><span>{formatCount(cell.volume)}</span>{cell.value!==null&&<small>{formatValue(activeMetric,cell.value)}</small>}</>;return <td key={cell.ts} title={`${entity.label} · ${new Date(cell.ts).toLocaleString('pt-BR')} · ${statusLabel(cell.status)} · ${formatCount(cell.volume)} plays · ${metrics[activeMetric]}: ${formatValue(activeMetric,cell.value)}${cell.baseline_value!==null?` · baseline ${formatValue(activeMetric,cell.baseline_value)}`:''}`}><button className="aggregate-cell" style={{'--cell-color':qualityColors[cell.status]} as CSSProperties} aria-label={`${entity.label}, ${formatTime(cell.ts,view.effective_granularity)}, ${statusLabel(cell.status)}, ${formatCount(cell.volume)} plays`} onClick={()=>setSelected({key:entity.dim_key,ts:cell.ts})}>{contents}</button>{href&&selected?.key===entity.dim_key&&selected.ts===cell.ts&&<Link className="aggregate-cell-link" to={href}>Sessões desta janela ↗</Link>}</td>;})}</tr>)}</tbody></table></div>}
   <div className="aggregate-pagination">{offset>0&&<button className="boards-button" onClick={()=>setOffset(Math.max(0,offset-10))}>Entidades anteriores</button>}{heatmapPages&&<button className="boards-button" onClick={()=>setOffset(view.heatmap.next_offset??offset+10)}>Mais entidades</button>}{timeOffset>0&&<button className="boards-button" onClick={()=>setTimeOffset(Math.max(0,timeOffset-36))}>Horários anteriores</button>}{hasMoreTime&&<button className="boards-button" onClick={()=>setTimeOffset(view.heatmap.next_time_offset!)}>Mais horários</button>}</div>
  </section>
   <div className="aggregate-lower-grid"><section className="aggregate-ranking-panel"><div className="aggregate-panel-heading"><div><h2>Ranking por impacto estimado</h2><p>Volume × excesso acima do SLA de atenção ({warning===undefined?'SLA indisponível':formatValue(activeMetric,warning)}).</p></div></div>{ranking.length?<ol className="aggregate-ranking">{ranking.slice(0,10).map((item,index)=><li key={item.dim_key}><span className="aggregate-rank-number">{index+1}</span><div className="aggregate-rank-main"><strong>{item.label}</strong><span>{formatCount(item.volume)} plays · {formatValue(activeMetric,item.value)} · {statusLabel(item.status)}</span><div className="aggregate-rank-bar"><i style={{width:`${Math.max(2,Math.min(100,item.impact_score/Math.max(1,ranking[0]?.impact_score??1)*100))}%`,background:qualityColors[item.status]}}/></div></div><b>{new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(item.impact_score)}<small>{item.impact_unit}</small></b></li>)}</ol>:<p className="aggregate-empty">Sem entidades com impacto neste recorte.</p>}<small className="aggregate-method-note">Score de priorização fornecido pelo servidor. Não representa usuários distintos.</small></section>
   <aside className="aggregate-inspector"><div className="boards-eyebrow">DETALHE DO BUCKET</div>{selectedEntry?<><span className="boards-chip">{dimensions[view.heatmap.dimension]}</span><h2>{selectedEntry.entity.label}</h2><p>{new Date(selectedEntry.cell.ts).toLocaleString('pt-BR')} · {view.effective_granularity}</p><dl><div><dt>Faixa</dt><dd>{statusLabel(selectedEntry.cell.status)}</dd></div><div><dt>{metrics[activeMetric]}</dt><dd>{formatValue(activeMetric,selectedEntry.cell.value)}</dd></div><div><dt>Volume</dt><dd>{formatCount(selectedEntry.cell.volume)} plays</dd></div><div><dt>Baseline do foco</dt><dd>{formatValue(activeMetric,selectedEntry.cell.baseline_value??baselineFor(selectedEntry.cell.ts)?.value)}</dd></div><div><dt>Diferença para baseline</dt><dd>{formatValue(activeMetric,selectedEntry.cell.baseline_delta)}</dd></div></dl>{activeMetric==='join_time_ms_avg'&&<div className="aggregate-percentiles"><strong>Percentis informados pela fonte</strong><span>p50 {formatValue(activeMetric,selectedEntry.cell.p50)} · p95 {formatValue(activeMetric,selectedEntry.cell.p95)} · p99 {formatValue(activeMetric,selectedEntry.cell.p99)}</span></div>}{drilldownHref(selectedEntry.entity,selectedEntry.cell.ts,selectedEntry.cell.status)?<Link className="boards-primary aggregate-evidence-link" to={drilldownHref(selectedEntry.entity,selectedEntry.cell.ts,selectedEntry.cell.status)!}>Abrir sessões desta janela ↗</Link>:<p className="aggregate-no-evidence">{selectedEntry.cell.status==='good'?'Este bucket está dentro do SLA.':board.linked_sessions_board_id?'Não há filtro de sessão aplicável a este bucket.':'Sem board de sessões vinculado. Vincule um board e envie as sessões reais desta dimensão e janela pelo agente.'}</p>}</>:<p>Selecione uma célula do heatmap para comparar com o baseline{activeMetric==='join_time_ms_avg'?' e ver percentis': ''}.</p>}{critical!==undefined&&<small>Bandas: saudável abaixo de {formatValue(activeMetric,warning)} · atenção abaixo de {formatValue(activeMetric,critical)} · crítico a partir do limite crítico.</small>}{sample&&<small>Dados de amostra: cobertura declarada {(coverage*100).toFixed(1)}%.</small>}</aside></div>
  <section className="aggregate-series-panel"><div className="aggregate-panel-heading"><div><h2>Série temporal</h2><p>{metrics[activeMetric]} e volume por intervalo. Anotações indicam desvios estatísticos da própria série.</p></div><span>{view.annotations.length} anotações</span></div><TimeSeries view={view} metric={activeMetric} granularity={view.effective_granularity??board.granularity}/></section>
 </div>;
}

function Provenance({board,coverage}:{board:Extract<ServerBoard,{board_type:'aggregate'}>;coverage:number}) {
 return <section className="aggregate-provenance"><div><span>FONTE</span><strong>{board.source.system}</strong><small>{board.source.query||'Consulta não informada'}</small></div><div><span>AMOSTRAGEM</span><strong>{board.source.sampling.method}</strong><small>{coverage<1?`Cobertura declarada ${(coverage*100).toFixed(1)}%`:'Cobertura declarada de 100% pela fonte'}</small></div><div><span>CONTAGEM</span><strong>{board.source.counting==='touch'?'Touch':'Play único'}</strong><small>{board.source.counting==='touch'?'Um play contado em cada POP que o entregou. Somar POPs pode ultrapassar o ISP.':'A fonte declara deduplicação de plays.'}</small></div></section>;
}

function TimeSeries({view,metric,granularity}:{view:AggregateView;metric:AggregateMetric;granularity:string}) {
 const points=view.series,annotations=view.annotations.filter(item=>!item.dim_key);
 if(!points.length)return <div className="aggregate-empty">Sem pontos temporais para exibir.</div>;
 const width=960,height=260,pad=36,values=points.flatMap(point=>point.value===null?[]:[point.value]),minValue=Math.min(0,...values),maxValue=Math.max(0.000001,...values),maxVolume=Math.max(1,...points.map(point=>point.volume));
 const x=(index:number)=>pad+(points.length===1?0:index*(width-pad*2)/(points.length-1));
 const y=(value:number)=>height-pad-(value-minValue)/(maxValue-minValue||1)*(height-pad*2);
 const line=points.map((point,index)=>point.value===null?'':`${index===0||points[index-1]?.value===null?'M':'L'} ${x(index)} ${y(point.value)}`).filter(Boolean).join(' ');
 return <div className="aggregate-series-scroll"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${metrics[metric]} e volume ao longo do tempo`} className="aggregate-series-chart">
  {points.map((point,index)=><g key={point.ts}><rect x={x(index)-Math.max(1,10-points.length/10)} y={height-pad-point.volume/maxVolume*62} width={Math.max(2,Math.min(12,(width-pad*2)/points.length*.68))} height={point.volume/maxVolume*62} fill="#63a8c2" opacity=".42"><title>{formatTime(point.ts,granularity)} · {formatCount(point.volume)} plays</title></rect></g>)}
  <path d={line} fill="none" stroke="#168c7d" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>
  {points.map((point,index)=>point.value===null?null:<circle key={point.ts} cx={x(index)} cy={y(point.value)} r="3.5" fill={qualityColors[point.status??'unknown']}><title>{formatTime(point.ts,granularity)} · {formatValue(metric,point.value)} · {formatCount(point.volume)} plays</title></circle>)}
  {annotations.map(annotation=>{const index=points.findIndex(point=>point.ts===annotation.ts);if(index<0)return null;const point=points[index];return point?.value===null||!point?null:<g key={`${annotation.ts}:${annotation.metric}`}><line x1={x(index)} x2={x(index)} y1={pad} y2={height-pad} stroke="#d17a42" strokeDasharray="4 4"/><text x={Math.min(width-12,x(index)+4)} y={pad+10} fill="#a45325" fontSize="10">z {annotation.z_score.toFixed(1)}</text><title>{annotation.direction==='up'?'Pico':'Queda'} · {new Date(annotation.ts).toLocaleString('pt-BR')}</title></g>;})}
  <text x={pad} y={height-8} fill="#8292a7" fontSize="10">{points[0]&&formatTime(points[0].ts,granularity)}</text><text x={width-pad} y={height-8} textAnchor="end" fill="#8292a7" fontSize="10">{points.at(-1)&&formatTime(points.at(-1)!.ts,granularity)}</text>
 </svg><div className="aggregate-series-legend"><span><i className="series-line"/>Métrica: {metrics[metric]} ({metric==='join_time_ms_avg'?'ms':'%'})</span><span><i className="series-volume"/>Volume de plays</span><span><i className="series-anomaly"/>Pico / queda detectada (z-score ≥ 3)</span></div><div className="aggregate-series-summary">{points.map(point=><span key={point.ts}><strong>{formatTime(point.ts,granularity)}</strong>{formatValue(metric,point.value)} · {formatCount(point.volume)} plays</span>)}</div></div>;
}
