import { useEffect, useState } from 'react';
import { useInfiniteQuery, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useVhAuth } from '../../auth/auth-context';
import { createServerBoard, deleteServerBoard, focusLabel, getServerBoard, getServerView, listServerBoards, SessionDrilldownParamsSchema, type CreateServerBoard, type SessionFilter } from './api';
import { Flow } from './Flow';
import { dimensions, focusDimensions, formatMetric, metricLabels, qualityColors, qualityLabels, statusFor, type BoardNode, type QualityMetric } from './data';
import { AggregateBoardDetail, AggregateCreateForm } from './AggregateBoard';
import './boards.css';
const errorText=(error:unknown)=>error instanceof Error?error.message:'Não foi possível carregar os dados.';
function drilldownFromSearch(params:URLSearchParams):{filters:SessionFilter[];context?:{time_window:{from:string;to:string};quality:'startup_error'|'warning_buffer'|'critical_buffer'|'warning_join'|'critical_join'|'any_sla_violation'}} {
 let rawFilters:unknown;
 const encoded=params.get('filters');
 if(encoded){try{rawFilters=JSON.parse(encoded);}catch{return {filters:[]};}}
 const input:Record<string,unknown>={};if(rawFilters!==undefined)input.filters=rawFilters;
 for(const key of ['dimension','entity','time_from','time_to','quality']){const value=params.get(key);if(value!==null)input[key]=value;}
 const parsed=SessionDrilldownParamsSchema.safeParse(input);
 if(!parsed.success)return {filters:[]};
 const toSessionFilter=(item:{dimension:'isp'|'pop'|'media_id'|'state'|'device_type';entity:string}):SessionFilter=>item.dimension==='media_id'?{dimension:'media',entity:item.entity}:{dimension:item.dimension,entity:item.entity};
 const filters=[...(parsed.data.filters??[]).map(toSessionFilter)];
 if(parsed.data.dimension&&parsed.data.entity)filters.push(toSessionFilter({dimension:parsed.data.dimension,entity:parsed.data.entity}));
 const unique=filters.filter((item,index)=>filters.findIndex(other=>other.dimension===item.dimension)===index).slice(0,4);
 const context=parsed.data.time_from&&parsed.data.time_to&&parsed.data.quality?{time_window:{from:parsed.data.time_from,to:parsed.data.time_to},quality:parsed.data.quality}:undefined;
 return {...{filters:unique},...(context?{context}:{})};
}
export default function BoardsPage() {
 const {userId}=useVhAuth();const navigate=useNavigate(),cache=useQueryClient();
 const query=useInfiniteQuery({queryKey:['boards',userId],initialPageParam:0,queryFn:({pageParam})=>listServerBoards(pageParam),getNextPageParam:last=>last.next_offset??undefined,refetchInterval:15000});
 const [creating,setCreating]=useState(false),[creatingKind,setCreatingKind]=useState<'sessions'|'aggregate'>('sessions'),[name,setName]=useState(''),[type,setType]=useState<'user'|'device'|'isp'|'pop'>('user'),[entity,setEntity]=useState(''),[deviceUser,setDeviceUser]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const [startupWarning,setStartupWarning]=useState('0.01'),[startupCritical,setStartupCritical]=useState('0.05'),[bufferWarning,setBufferWarning]=useState('0.02'),[bufferCritical,setBufferCritical]=useState('0.05');
 const [joinWarning,setJoinWarning]=useState('2000'),[joinCritical,setJoinCritical]=useState('5000');
 const boards=query.data?.pages.flatMap(page=>page.boards)??[];
 async function create() {
  const focus:CreateServerBoard['focus']=type==='device'?{type,user_id:deviceUser.trim(),device_id:entity.trim()}:type==='user'?{type,user_id:entity.trim()}:type==='isp'?{type,isp:entity.trim()}:{type,pop:entity.trim()};
  setSaving(true);setError('');try{const board=await createServerBoard({name:name.trim(),focus,slas:{startup_error_rate:{warning:Number(startupWarning),critical:Number(startupCritical)},buffer_ratio:{warning:Number(bufferWarning),critical:Number(bufferCritical)},join_time_ms:{warning:Number(joinWarning),critical:Number(joinCritical)}}});await cache.invalidateQueries({queryKey:['boards',userId]});navigate(board.view_path);}catch(error){setError(errorText(error));}finally{setSaving(false);}
 }
 return <div className="boards-page"><div className="boards-heading"><div><div className="boards-eyebrow">STREAMING OBSERVABILITY</div><h1>Seus boards</h1><p>Explore sessões individuais ou acompanhe métricas agregadas por entidade e janela.</p></div><button className="boards-primary" onClick={()=>setCreating(true)}>＋ Criar board</button></div>
  <div className="boards-notice">Agentes podem criar boards e enviar sessões pelo MCP. <Link to="/dashboard/mcp">Conectar agente →</Link> · <Link to="/dashboard/boards/demos">Experimentar demos locais</Link></div>
  {creating&&<><div className="boards-create-switch" role="group" aria-label="Tipo de board"><button className="boards-button" aria-pressed={creatingKind==='sessions'} onClick={()=>setCreatingKind('sessions')}>Sessões</button><button className="boards-button" aria-pressed={creatingKind==='aggregate'} onClick={()=>setCreatingKind('aggregate')}>Agregado</button></div>{creatingKind==='aggregate'?<AggregateCreateForm boards={boards} onCancel={()=>setCreating(false)} onCreated={path=>{void cache.invalidateQueries({queryKey:['boards',userId]});navigate(path);}}/>:<form className="boards-create" onSubmit={e=>{e.preventDefault();void create();}}><div className="boards-section-heading"><h2>Novo board de sessões</h2><button type="button" className="boards-button" onClick={()=>setCreating(false)}>Cancelar</button></div>
   <div className="boards-form-grid"><label>Nome<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Tipo<select value={type} onChange={e=>{setType(e.target.value as typeof type);setEntity('');}}>{focusDimensions.map(d=><option key={d.key} value={d.key}>{d.label}</option>)}</select></label><label>{type==='user'?'User ID':type==='device'?'Device ID':type==='isp'?'ISP':'POP'}<input required maxLength={128} value={entity} onChange={e=>setEntity(e.target.value)}/></label>{type==='device'&&<label>User ID do device<input required maxLength={128} value={deviceUser} onChange={e=>setDeviceUser(e.target.value)}/></label>}</div>
   <p className="boards-sla-explanation">Defina as faixas de SLA. Taxas em 0–1: 0.01 = 1%. Saudável abaixo de atenção; crítico a partir do limite crítico.</p>
   <div className="boards-sla-form">{[['Erro de startup · atenção',startupWarning,setStartupWarning],['Erro de startup · crítico',startupCritical,setStartupCritical],['Buffer ratio · atenção',bufferWarning,setBufferWarning],['Buffer ratio · crítico',bufferCritical,setBufferCritical]].map(([label,value,setter])=><label key={String(label)}>{String(label)}<input required type="number" min="0" max="1" step="any" value={String(value)} onChange={e=>(setter as (value:string)=>void)(e.target.value)}/></label>)}</div>
   <div className="boards-sla-form"><label>Join time · atenção (ms)<input required type="number" min="0" max="86400000" value={joinWarning} onChange={e=>setJoinWarning(e.target.value)}/></label><label>Join time · crítico (ms)<input required type="number" min="0" max="86400000" value={joinCritical} onChange={e=>setJoinCritical(e.target.value)}/></label></div>
   {error&&<p role="alert">{error}</p>}<button disabled={saving} className="boards-primary">{saving?'Criando…':'Criar board'}</button></form>}</>}
  {query.isPending&&<p>Carregando boards…</p>}{query.error&&<p role="alert">{errorText(query.error)} <button className="boards-button" onClick={()=>void query.refetch()}>Tentar novamente</button></p>}
  {!query.isPending&&!query.error&&!boards.length&&<div className="boards-empty">Nenhum board ainda. Crie um board ou peça ao seu agente para criar pelo MCP.</div>}
  <div className="boards-card-grid">{boards.map(board=>{const aggregate=board.board_type==='aggregate';const focusLabelFor=dimensions.find(d=>d.key===board.focus.type)?.label??(board.focus.type==='state'?'Estado / UF':board.focus.type==='media_id'?'Mídia':'Tipo de device');return <article className="boards-card" key={board.id}><div className="boards-card-top"><span className="boards-chip">{aggregate?'Agregado · ':''}{focusLabelFor}</span>{aggregate&&board.source.sampling.coverage<1?<span className="aggregate-badge sample">Amostra · {(board.source.sampling.coverage*100).toFixed(1)}%</span>:<span className="boards-signal">Dados do agente</span>}</div><Link to={board.view_path}><h2>{board.name}</h2></Link><p>{focusLabel(board)}</p><div className="boards-card-stats"><div><strong>{aggregate?board.bucket_count:board.session_count}</strong><span>{aggregate?'buckets recebidos':'sessões recebidas'}</span></div></div><footer><span>{aggregate?'Volume e métricas por bucket':'SLAs definidos neste board'}</span><Link to={board.view_path}>Explorar ↗</Link></footer><button className="boards-delete" onClick={async()=>{if(!window.confirm(`Excluir “${board.name}” e seus dados?`))return;try{await deleteServerBoard(board.id);await cache.invalidateQueries({queryKey:['boards',userId]});}catch(error){setError(errorText(error));}}}>Excluir board</button></article>;})}</div>
  {query.hasNextPage&&<button className="boards-button" disabled={query.isFetchingNextPage} onClick={()=>void query.fetchNextPage()}>Carregar mais boards</button>}{error&&!creating&&<p role="alert">{error}</p>}
 </div>;
}
export function BoardDetailPage() {
 const {boardId}=useParams(),{userId}=useVhAuth();
 const query=useQuery({queryKey:['board-record',userId,boardId],queryFn:()=>getServerBoard(boardId!),enabled:!!boardId,refetchInterval:30000});
 if(query.isPending)return <div className="boards-page">Carregando board…</div>;
 if(!query.data||query.error)return <div className="boards-page"><Link to="/dashboard/boards">← Todos os boards</Link><p role="alert">{errorText(query.error)}</p><button className="boards-button" onClick={()=>void query.refetch()}>Tentar novamente</button></div>;
 return query.data.board_type==='aggregate'?<AggregateBoardDetail board={query.data} userId={userId}/>:<SessionBoardDetail key={`${query.data.id}:${window.location.search}`} boardId={query.data.id} userId={userId}/>;
}
function SessionBoardDetail({boardId,userId}:{boardId:string;userId:string|null}) {
 const [searchParams]=useSearchParams();const searchKey=searchParams.toString();const drilldown=drilldownFromSearch(searchParams);const [filters,setFilters]=useState<SessionFilter[]>(drilldown.filters),[selectedId,setSelectedId]=useState<string|null>(null),[metric,setMetric]=useState<QualityMetric>('startup_error_rate');
 useEffect(()=>{setFilters(drilldown.filters);setSelectedId(null);setMetric('startup_error_rate');},[boardId,searchKey]);
 const query=useQuery({queryKey:['board-view',userId,boardId,filters,drilldown.context],queryFn:()=>getServerView(boardId,filters,drilldown.context),enabled:!!boardId,refetchInterval:5000});
 const view=query.data;
 if(query.isPending)return <div className="boards-page">Carregando board…</div>;
 if(!view||query.error)return <div className="boards-page"><Link to="/dashboard/boards">← Todos os boards</Link><p role="alert">{errorText(query.error)}</p><button className="boards-button" onClick={()=>void query.refetch()}>Tentar novamente</button></div>;
 const board=view.board,selected=view.nodes.find(node=>node.id===selectedId)??view.nodes.find(node=>node.dimension===board.focus.type),available=(['startup_error_rate','buffer_ratio','join_time_ms'] as const).filter(name=>board.slas[name]);const currentMetric=available.includes(metric)?metric:'startup_error_rate';const metricData=view.metrics[currentMetric];
 const boundary=(value:number)=>formatMetric({value,status:'good',unit:currentMetric==='join_time_ms'?'ms':'ratio'});
 const notes=`SLA: saudável < ${boundary(metricData?.sla.warning??0)} · atenção < ${boundary(metricData?.sla.critical??0)} · crítico ≥ ${boundary(metricData?.sla.critical??0)}`;
 function select(node:BoardNode){setSelectedId(node.id);const filter=node.filter;if(filter&&filter.dimension!==board.focus.type&&!filters.some(item=>item.dimension===filter.dimension)){setFilters(previous=>[...previous,filter]);}}
 function returnTo(count:number){setFilters(previous=>previous.slice(0,count));setSelectedId(null);}
 const status=statusFor(metricData);
 return <div className="boards-page boards-detail"><Link className="boards-back" to="/dashboard/boards">← Todos os boards</Link><div className="boards-heading"><div><div className="boards-eyebrow">SLA EXPLORER</div><h1>{board.name}</h1><p>{focusLabel(board)}</p></div></div>
  {drilldown.context&&<div className="boards-notice">Evidência da janela {new Date(drilldown.context.time_window.from).toLocaleString('pt-BR')} — {new Date(drilldown.context.time_window.to).toLocaleString('pt-BR')}. Qualidade recalculada pelos SLAs deste board de sessões; as bandas podem diferir das do board agregado.</div>}
  <nav className="boards-breadcrumb" aria-label="Filtros do board"><button className="boards-button" disabled={!filters.length} onClick={()=>returnTo(filters.length-1)}>← Voltar</button><ol><li><button onClick={()=>returnTo(0)}><small>Board completo</small>{focusLabel(board)}</button></li>{filters.map((filter,index)=><li key={filter.dimension}><button aria-current={index===filters.length-1?'location':undefined} onClick={()=>returnTo(index+1)}><small>{dimensions.find(d=>d.key===filter.dimension)?.label??(filter.dimension==='state'?'Estado / UF':filter.dimension==='device_type'?'Tipo de device':'Mídia')}</small>{filter.dimension==='device'?`${filter.user_id} · ${filter.entity}`:filter.entity}</button></li>)}</ol>{!!filters.length&&<button className="boards-button" onClick={()=>returnTo(0)}>Limpar filtros</button>}</nav>
  <div className="boards-metrics"><div><span>Sessões no recorte</span><strong>{view.sessionCount}</strong><small>Dentro do foco deste board</small></div><div><span>{metricLabels[currentMetric]}</span><strong>{formatMetric(metricData)}</strong><small>{currentMetric==='startup_error_rate'?'Falhas / todas as sessões':'Média das sessões com startup bem-sucedido'}</small></div><div><span>Faixa do SLA</span><strong>{qualityLabels[status]}</strong><small>{metricData?.sample_count??0} amostras</small></div><div><span>{currentMetric==='startup_error_rate'?'Falhas de startup':'Sessões no limite crítico'}</span><strong>{metricData?.violations??0}</strong><small>Denominador: {metricData?.sample_count??0} sessões</small></div></div>
  <div className="boards-workspace"><section className="boards-canvas"><div className="boards-section-heading"><div><h2>Fluxo por SLA</h2><p>{view.columns.map(d=>dimensions.find(item=>item.key===d)!.label).join(' → ')}</p><p>Clique para restringir as sessões deste board.</p></div><div className="boards-metric-switch" role="group" aria-label="View por SLA">{available.map(name=><button key={name} aria-pressed={currentMetric===name} onClick={()=>setMetric(name)}>{metricLabels[name]}</button>)}</div></div><div className="boards-thresholds">{notes}<small>Falhas de startup não entram em buffer ratio ou join time. Sem amostras = sem dados.</small></div><div className="boards-legend">{Object.entries(qualityLabels).map(([key,label])=><span key={key}><i style={{background:qualityColors[key as keyof typeof qualityColors]}}/>{label}</span>)}<span>Largura = sessões · Faixas = qualidade por sessão · Outros não é filtrável</span></div>{view.sessionCount?<Flow key={`${board.id}:${view.id}:${currentMetric}`} view={view} columns={view.columns} metric={currentMetric} notes={notes} selectedId={selectedId} onSelect={select}/>:<div className="boards-empty">Nenhuma sessão neste recorte. Envie sessões pelo agente ou limpe os filtros.</div>}</section>
   <aside className="boards-inspector"><div className="boards-eyebrow">DETALHES DO RECORTE</div>{selected&&<><span className="boards-chip">{dimensions.find(d=>d.key===selected.dimension)!.label}</span><h2>{selected.label}</h2>{selected.model&&<p>Modelo: {selected.model}</p>}<p>{selected.volume} sessões</p><div className="boards-quality-bar"><i style={{background:qualityColors[statusFor(selected.metrics[currentMetric])],width:'100%'}}/></div><dl><div><dt>{metricLabels[currentMetric]}</dt><dd>{formatMetric(selected.metrics[currentMetric])}</dd></div><div><dt>Amostras</dt><dd>{selected.metrics[currentMetric]?.sample_count??0}</dd></div><div><dt>Limite crítico</dt><dd>{selected.metrics[currentMetric]?.violations??0} sessões</dd></div></dl></>}<div className="boards-comparison"><strong>SLAs deste board</strong><p>{notes}</p></div><small>Startup usa todas as sessões. Buffer ratio e join time usam média aritmética de sucessos, sem ponderação por duração.</small></aside>
  </div>
 </div>;
}
