import { useEffect, useState } from 'react';
import { useInfiniteQuery, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useVhAuth } from '../../auth/auth-context';
import { createServerBoard, deleteServerBoard, focusLabel, getServerView, listServerBoards, type CreateServerBoard } from './api';
import { Flow } from './Flow';
import { dimensions, focusDimensions, formatMetric, metricLabels, qualityColors, qualityLabels, statusFor, type BoardFilter, type BoardNode, type QualityMetric } from './data';
import './boards.css';
const errorText=(error:unknown)=>error instanceof Error?error.message:'Não foi possível carregar os dados.';
export default function BoardsPage() {
 const {userId}=useVhAuth();const navigate=useNavigate(),cache=useQueryClient();
 const query=useInfiniteQuery({queryKey:['boards',userId],initialPageParam:0,queryFn:({pageParam})=>listServerBoards(pageParam),getNextPageParam:last=>last.next_offset??undefined,refetchInterval:15000});
 const [creating,setCreating]=useState(false),[name,setName]=useState(''),[type,setType]=useState<'user'|'device'|'isp'|'pop'>('user'),[entity,setEntity]=useState(''),[deviceUser,setDeviceUser]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const [startupWarning,setStartupWarning]=useState('0.01'),[startupCritical,setStartupCritical]=useState('0.05'),[bufferWarning,setBufferWarning]=useState('0.02'),[bufferCritical,setBufferCritical]=useState('0.05');
 const [joinWarning,setJoinWarning]=useState('2000'),[joinCritical,setJoinCritical]=useState('5000');
 const boards=query.data?.pages.flatMap(page=>page.boards)??[];
 async function create() {
  const focus:CreateServerBoard['focus']=type==='device'?{type,user_id:deviceUser.trim(),device_id:entity.trim()}:type==='user'?{type,user_id:entity.trim()}:type==='isp'?{type,isp:entity.trim()}:{type,pop:entity.trim()};
  setSaving(true);setError('');try{const board=await createServerBoard({name:name.trim(),focus,slas:{startup_error_rate:{warning:Number(startupWarning),critical:Number(startupCritical)},buffer_ratio:{warning:Number(bufferWarning),critical:Number(bufferCritical)},join_time_ms:{warning:Number(joinWarning),critical:Number(joinCritical)}}});await cache.invalidateQueries({queryKey:['boards',userId]});navigate(board.view_path);}catch(error){setError(errorText(error));}finally{setSaving(false);}
 }
 return <div className="boards-page"><div className="boards-heading"><div><div className="boards-eyebrow">STREAMING OBSERVABILITY</div><h1>Seus boards</h1><p>Monitore as sessões enviadas pelos seus agentes com os SLAs de cada board.</p></div><button className="boards-primary" onClick={()=>setCreating(true)}>＋ Criar board</button></div>
  <div className="boards-notice">Agentes podem criar boards e enviar sessões pelo MCP. <Link to="/dashboard/mcp">Conectar agente →</Link> · <Link to="/dashboard/boards/demos">Experimentar demos locais</Link></div>
  {creating&&<form className="boards-create" onSubmit={e=>{e.preventDefault();void create();}}><div className="boards-section-heading"><h2>Novo board</h2><button type="button" className="boards-button" onClick={()=>setCreating(false)}>Cancelar</button></div>
   <div className="boards-form-grid"><label>Nome<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Tipo<select value={type} onChange={e=>{setType(e.target.value as typeof type);setEntity('');}}>{focusDimensions.map(d=><option key={d.key} value={d.key}>{d.label}</option>)}</select></label><label>{type==='user'?'User ID':type==='device'?'Device ID':type==='isp'?'ISP':'POP'}<input required maxLength={128} value={entity} onChange={e=>setEntity(e.target.value)}/></label>{type==='device'&&<label>User ID do device<input required maxLength={128} value={deviceUser} onChange={e=>setDeviceUser(e.target.value)}/></label>}</div>
   <p className="boards-sla-explanation">Defina as faixas de SLA. Taxas em 0–1: 0.01 = 1%. Saudável abaixo de atenção; crítico a partir do limite crítico.</p>
   <div className="boards-sla-form">{[['Erro de startup · atenção',startupWarning,setStartupWarning],['Erro de startup · crítico',startupCritical,setStartupCritical],['Buffer ratio · atenção',bufferWarning,setBufferWarning],['Buffer ratio · crítico',bufferCritical,setBufferCritical]].map(([label,value,setter])=><label key={String(label)}>{String(label)}<input required type="number" min="0" max="1" step="any" value={String(value)} onChange={e=>(setter as (value:string)=>void)(e.target.value)}/></label>)}</div>
   <div className="boards-sla-form"><label>Join time · atenção (ms)<input required type="number" min="0" max="86400000" value={joinWarning} onChange={e=>setJoinWarning(e.target.value)}/></label><label>Join time · crítico (ms)<input required type="number" min="0" max="86400000" value={joinCritical} onChange={e=>setJoinCritical(e.target.value)}/></label></div>
   {error&&<p role="alert">{error}</p>}<button disabled={saving} className="boards-primary">{saving?'Criando…':'Criar board'}</button></form>}
  {query.isPending&&<p>Carregando boards…</p>}{query.error&&<p role="alert">{errorText(query.error)} <button className="boards-button" onClick={()=>void query.refetch()}>Tentar novamente</button></p>}
  {!query.isPending&&!query.error&&!boards.length&&<div className="boards-empty">Nenhum board ainda. Crie um board ou peça ao seu agente para criar pelo MCP.</div>}
  <div className="boards-card-grid">{boards.map(board=><article className="boards-card" key={board.id}><div className="boards-card-top"><span className="boards-chip">{dimensions.find(d=>d.key===board.focus.type)!.label}</span><span className="boards-signal">Dados do agente</span></div><Link to={board.view_path}><h2>{board.name}</h2></Link><p>{focusLabel(board)}</p><div className="boards-card-stats"><div><strong>{board.session_count}</strong><span>sessões recebidas</span></div></div><footer><span>SLAs definidos neste board</span><Link to={board.view_path}>Explorar ↗</Link></footer><button className="boards-delete" onClick={async()=>{if(!window.confirm(`Excluir “${board.name}” e suas sessões?`))return;try{await deleteServerBoard(board.id);await cache.invalidateQueries({queryKey:['boards',userId]});}catch(error){setError(errorText(error));}}}>Excluir board</button></article>)}</div>
  {query.hasNextPage&&<button className="boards-button" disabled={query.isFetchingNextPage} onClick={()=>void query.fetchNextPage()}>Carregar mais boards</button>}{error&&!creating&&<p role="alert">{error}</p>}
 </div>;
}
export function BoardDetailPage() {
 const {boardId}=useParams(),{userId}=useVhAuth();const [filters,setFilters]=useState<BoardFilter[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[metric,setMetric]=useState<QualityMetric>('startup_error_rate');
 useEffect(()=>{setFilters([]);setSelectedId(null);setMetric('startup_error_rate');},[boardId]);
 const query=useQuery({queryKey:['board-view',userId,boardId,filters],queryFn:()=>getServerView(boardId!,filters),enabled:!!boardId,refetchInterval:5000});
 const view=query.data;
 if(query.isPending)return <div className="boards-page">Carregando board…</div>;
 if(!view||query.error)return <div className="boards-page"><Link to="/dashboard/boards">← Todos os boards</Link><p role="alert">{errorText(query.error)}</p><button className="boards-button" onClick={()=>void query.refetch()}>Tentar novamente</button></div>;
 const board=view.board,selected=view.nodes.find(node=>node.id===selectedId)??view.nodes.find(node=>node.dimension===board.focus.type),available=(['startup_error_rate','buffer_ratio','join_time_ms'] as const).filter(name=>board.slas[name]);const currentMetric=available.includes(metric)?metric:'startup_error_rate';const metricData=view.metrics[currentMetric];
 const boundary=(value:number)=>formatMetric({value,status:'good',unit:currentMetric==='join_time_ms'?'ms':'ratio'});
 const notes=`SLA: saudável < ${boundary(metricData?.sla.warning??0)} · atenção < ${boundary(metricData?.sla.critical??0)} · crítico ≥ ${boundary(metricData?.sla.critical??0)}`;
 function select(node:BoardNode){setSelectedId(node.id);const filter=node.filter;if(filter&&filter.dimension!==board.focus.type&&!filters.some(item=>item.dimension===filter.dimension)){setFilters(previous=>[...previous,filter]);}}
 function returnTo(count:number){setFilters(previous=>previous.slice(0,count));setSelectedId(null);}
 const status=statusFor(metricData);
 return <div className="boards-page boards-detail"><Link className="boards-back" to="/dashboard/boards">← Todos os boards</Link><div className="boards-heading"><div><div className="boards-eyebrow">SLA EXPLORER</div><h1>{board.name}</h1><p>{focusLabel(board)}</p></div></div>
  <nav className="boards-breadcrumb" aria-label="Filtros do board"><button className="boards-button" disabled={!filters.length} onClick={()=>returnTo(filters.length-1)}>← Voltar</button><ol><li><button onClick={()=>returnTo(0)}><small>Board completo</small>{focusLabel(board)}</button></li>{filters.map((filter,index)=><li key={filter.dimension}><button aria-current={index===filters.length-1?'location':undefined} onClick={()=>returnTo(index+1)}><small>{dimensions.find(d=>d.key===filter.dimension)!.label}</small>{filter.dimension==='device'?`${filter.user_id} · ${filter.entity}`:filter.entity}</button></li>)}</ol>{!!filters.length&&<button className="boards-button" onClick={()=>returnTo(0)}>Limpar filtros</button>}</nav>
  <div className="boards-metrics"><div><span>Sessões no recorte</span><strong>{view.sessionCount}</strong><small>Dentro do foco deste board</small></div><div><span>{metricLabels[currentMetric]}</span><strong>{formatMetric(metricData)}</strong><small>{currentMetric==='startup_error_rate'?'Falhas / todas as sessões':'Média das sessões com startup bem-sucedido'}</small></div><div><span>Faixa do SLA</span><strong>{qualityLabels[status]}</strong><small>{metricData?.sample_count??0} amostras</small></div><div><span>{currentMetric==='startup_error_rate'?'Falhas de startup':'Sessões no limite crítico'}</span><strong>{metricData?.violations??0}</strong><small>Denominador: {metricData?.sample_count??0} sessões</small></div></div>
  <div className="boards-workspace"><section className="boards-canvas"><div className="boards-section-heading"><div><h2>Fluxo por SLA</h2><p>{view.columns.map(d=>dimensions.find(item=>item.key===d)!.label).join(' → ')}</p><p>Clique para restringir as sessões deste board.</p></div><div className="boards-metric-switch" role="group" aria-label="View por SLA">{available.map(name=><button key={name} aria-pressed={currentMetric===name} onClick={()=>setMetric(name)}>{metricLabels[name]}</button>)}</div></div><div className="boards-thresholds">{notes}<small>Falhas de startup não entram em buffer ratio ou join time. Sem amostras = sem dados.</small></div><div className="boards-legend">{Object.entries(qualityLabels).map(([key,label])=><span key={key}><i style={{background:qualityColors[key as keyof typeof qualityColors]}}/>{label}</span>)}<span>Largura = sessões · Faixas = qualidade por sessão · Outros não é filtrável</span></div>{view.sessionCount?<Flow key={`${board.id}:${view.id}:${currentMetric}`} view={view} columns={view.columns} metric={currentMetric} notes={notes} selectedId={selectedId} onSelect={select}/>:<div className="boards-empty">Nenhuma sessão neste recorte. Envie sessões pelo agente ou limpe os filtros.</div>}</section>
   <aside className="boards-inspector"><div className="boards-eyebrow">DETALHES DO RECORTE</div>{selected&&<><span className="boards-chip">{dimensions.find(d=>d.key===selected.dimension)!.label}</span><h2>{selected.label}</h2>{selected.model&&<p>Modelo: {selected.model}</p>}<p>{selected.volume} sessões</p><div className="boards-quality-bar"><i style={{background:qualityColors[statusFor(selected.metrics[currentMetric])],width:'100%'}}/></div><dl><div><dt>{metricLabels[currentMetric]}</dt><dd>{formatMetric(selected.metrics[currentMetric])}</dd></div><div><dt>Amostras</dt><dd>{selected.metrics[currentMetric]?.sample_count??0}</dd></div><div><dt>Limite crítico</dt><dd>{selected.metrics[currentMetric]?.violations??0} sessões</dd></div></dl></>}<div className="boards-comparison"><strong>SLAs deste board</strong><p>{notes}</p></div><small>Startup usa todas as sessões. Buffer ratio e join time usam média aritmética de sucessos, sem ponderação por duração.</small></aside>
  </div>
 </div>;
}
