import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import type { BoardRepository } from "../../../application/ports/board-repository.js";
import { createBoard, getBoard, getBoardView, ingestBoardSessions, boardSchemaDescription } from "../../../application/use-cases/boards.js";
import { BoardIdSchema, CreateBoardSchema, IngestBoardSessionsSchema, BoardViewRequestSchema, BoardPageSchema } from "../../../domain/boards.js";
export function registerBoardTools(server: McpServer, boards: BoardRepository, ownerId: string, result: (run:()=>Record<string,unknown>)=>Promise<CallToolResult>) {
  server.registerTool("get_board_schema",{description:"Discover the session/SLA contract, units, limits and complete valid examples. Boards aggregate the authenticated owner's sessions deterministically; device identity includes user_id.",inputSchema:z.object({}).strict(),annotations:{readOnlyHint:true,openWorldHint:false}},()=>result(()=>boardSchemaDescription));
  server.registerTool("create_board",{description:"Create an owned monitoring board with explicit SLA warning/critical bands. Rates and buffer ratios use 0..1; join time uses ms. Returns view_path to open in Video Harness. No implicit SLA defaults.",inputSchema:CreateBoardSchema,annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},input=>result(()=>createBoard(boards,ownerId,input)));
  server.registerTool("list_boards",{description:"List the token owner's monitoring boards with session counts, paginated; no raw session payloads.",inputSchema:BoardPageSchema,annotations:{readOnlyHint:true,openWorldHint:false}},({offset,limit})=>result(()=>boards.list(ownerId,offset,limit)));
  server.registerTool("get_board",{description:"Read an owned board's focus, SLAs, count and view_path.",inputSchema:z.object({board_id:BoardIdSchema}).strict(),annotations:{readOnlyHint:true,openWorldHint:false}},({board_id})=>result(()=>getBoard(boards,ownerId,board_id)));
  server.registerTool("ingest_board_sessions",{description:"Atomically upsert at most 50 sessions by session_id within an owned board. Entire MCP body must also fit 32 KiB; send small batches. Failed startup forbids join_time_ms/buffer_ratio; successful startup requires both. Invalid batches write nothing.",inputSchema:z.object({board_id:BoardIdSchema,sessions:IngestBoardSessionsSchema.innerType().shape.sessions}).strict(),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false}},({board_id,sessions})=>result(()=>ingestBoardSessions(boards,ownerId,board_id,{sessions})));
  server.registerTool("list_board_sessions",{description:"Read raw sessions of an owned board in pages of at most 50; use get_board_view for its SLA graph.",inputSchema:BoardPageSchema.extend({board_id:BoardIdSchema}).strict(),annotations:{readOnlyHint:true,openWorldHint:false}},({board_id,offset,limit})=>result(()=>{getBoard(boards,ownerId,board_id);return boards.sessions(ownerId,board_id,offset,limit);}));
  server.registerTool("get_board_view",{description:"Read the deterministic SLA graph of an owned board. AND filters narrow its fixed focus. Device filter requires both entity=device.id and user_id. Rates use all startups; buffer/join means use successful sessions only, not duration weighting. Up to 8 entities + Others per layer.",inputSchema:z.object({board_id:BoardIdSchema,filters:BoardViewRequestSchema.innerType().shape.filters}).strict(),annotations:{readOnlyHint:true,openWorldHint:false}},({board_id,filters})=>result(()=>getBoardView(boards,ownerId,board_id,{filters})));
}
